---
- name: Download and deploy Focalboard
  hosts: focalboard
  become: yes

  tasks:
    - name: Ensure system is up to date
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      tags:
        - [update]

    - name: Deploy Portainer Agent
      include_role:
        name: docker_service_deploy
      vars:
        service_name: portainer_agent

    - name: Deploy focalboard
      include_role:
        name: docker_service_deploy
      vars:
        service_name: focalboard
