---
- name: Restart SSH
  service:
    name: ssh
    state: restarted

- name: Restart PVE Proxy
  service:
    name: pveproxy
    state: restarted

- name: Update Grub
  command: update-grub

- name: Reboot Host
  reboot:
    msg: "Reboot initiated by Ansible"
    reboot_timeout: 600
