---
- name: Download and deploy Wireguard
  hosts: syncthing
  become: yes

  tasks:
    - name: Ensure system is up to date
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      tags:
        - update

    - name: Deploy Portainer Agent
      include_role:
        name: docker_service_deploy
      vars:
        service_name: portainer_agent

    - name: Deploy Wireguard
      include_role:
        name: docker_service_deploy
      vars:
        service_name: wireguard
