---
pve_cpu_governor_intel: "conservative"
pve_cpu_governor_amd: "powersave"
pve_swappiness: 10

pve_remove_local_lvm: true
pve_enable_fstrim: true
pve_manage_repos: true
pve_remove_subscription_nag: true
pve_configure_ups: true

pve_api_user: "provisioner"
pve_api_token_name: "provisioner"

pve_api_password: "terraform"

pve_create_api_tokens: true
pve_create_root_api_token: false
