---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install QEMU Guest Agent (only if running under QEMU)
  ansible.builtin.package:
    name: qemu-guest-agent
    state: present
  when: ansible_system_vendor is defined and ansible_system_vendor == "QEMU"

- name: Ensure QEMU Guest Agent service is enabled and started
  ansible.builtin.service:
    name: qemu-guest-agent
    state: started
    enabled: true
  when: ansible_system_vendor is defined and ansible_system_vendor == "QEMU"
