[pve]
proxmox ansible_host=192.168.1.75 ansible_user=root

[vms]
omv ansible_host=192.168.1.212 ansible_user=root

[lxcs]
# template ansible_host=192.168.1.x ansible_user=root
# overleaf ansible_host=192.168.1.x ansible_user=root
# vikunja ansible_host=192.168.1.218 ansible_user=root
immich ansible_host=192.168.1.210 ansible_user=root
nextcloud ansible_host=192.168.1.208 ansible_host=root
focalboard ansible_host=192.168.1.218 ansible_user=root
actual-budget ansible_host=192.168.1.219 ansible_user=root
paperless-ngx ansible_host=192.168.1.213 ansible_user=root
byte-stash ansible_host=192.168.1.xxx ansible_user=root
