plugin: community.general.proxmox
url: https://192.168.1.100:8006
user: root@pam
password: "your_password_here" # Or use a token/key for better security
verify_ssl: false

groups:
  docker_hosts: "tags contains 'docker'"
  adguard_nodes: "tags contains 'dns'"

compose:
  ansible_host: proxmox_agent_networks[0].ip_addresses[0]
