---
- name: Configure Reverse Proxy
  hosts: caddy
  become: yes

  tasks:
    - name: Ensure system is up to date
      ansible.builtin.apt:
        upgrade: dist
        update_cache: yes
      tags:
        - update

    - name: Deploy Portainer Agent
      include_role:
        name: docker_service_deploy
      vars:
        service_name: portainer_agent

    - name: Deploy caddy
      include_role:
        name: docker_service_deploy
      vars:
        service_name: caddy

    - name: Configure Caddyfiles
      include_role:
        name: reverse_proxy
      vars:
        domain: "jmnogueira.pt"
        email: "jomouzio@gmail.com"
