---

- name: Create IaC Provisioner Role
  command: >
  pveum role add TerraformAdmin -privs 
  "VM.Allocate VM.Clone VM.Config.CDROM VM.Config.Cloudinit VM.Config.CPU VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Monitor VM.Audit VM.PowerMgmt Datastore.Allocate Datastore.AllocateSpace Datastore.Audit SDN.Use Sys.Audit Sys.Modify"
  failed_when: false

- name: Create Terraform Service User
  community.general.proxmox_user:
    name: "{{ pve_api_user }}@pve"
    password: "{{ vault_pve_service_password }}"
    role: "Provisioner"
    state: present

- name: Check if API Token exists
  shell: pveum user token list {{ pve_api_user }}@pve | grep -q 'terraform-token'
  register: token_check
  failed_when: false
  changed_when: false

- name: Generate API Token
  shell: pveum user token add {{ pve_api_user }}@pve terraform-token --privsep 0
  register: token_output
  when: token_check.rc != 0

- name: Ensure Ansible SSH keypair exists on local machine
  openssh_keypair:
    path: "~/.ssh/ansible"
    type: ed25519
    comment: "ansible-svc-key"
  delegate_to: localhost
  run_once: true

- name: Ensure SSH Key is authorized for root
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"

- name: Disable Password Authentication for SSH
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: Restart SSH
