---
- name: Ensure mount points exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ storage_devices }}"

- name: Create filesystem on devices
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "/dev/disk/by-id/{{ item.id }}"
    force: no
  loop: "{{ storage_devices }}"

- name: Mount storage devices by ID (Stable)
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "/dev/disk/by-id/{{ item.id }}"
    fstype: "{{ item.fstype }}"
    opts: "defaults,nofail"
    state: mounted
  loop: "{{ storage_devices }}"
  register: disk_mounts

- name: Show mount status
  ansible.builtin.debug:
    msg: "Device {{ item.item.name }} mounted at {{ item.item.path }}"
  loop: "{{ disk_mounts.results }}"
  when: item.changed

- name: Register devices as Proxmox Datastores
  ansible.builtin.command: >
    pvesm add dir {{ item.datastore_name }}
    --path {{ item.path }}
    --content images,rootdir
  loop: "{{ storage_devices }}"
  register: pvesm_result
  failed_when:
    - pvesm_result.rc != 0
    - "'already defined' not in pvesm_result.stderr"
  changed_when: pvesm_result.rc == 0

- name: Create application data directories on Devices
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    # preparing for LXC mount
    owner: "100000"
    group: "100000"
    mode: '0755'
  loop: "{{ storage_folders }}"
