---
- name: Disable the Proxmox Enterprise repositories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    # Proxmox 9.x
    - /etc/apt/sources.list.d/pve-enterprise.sources
    - /etc/apt/sources.list.d/ceph.sources
    # Proxmox <= 8
    - /etc/apt/sources.list.d/pve-enterprise.lists
    - /etc/apt/sources.list.d/ceph.lists

- name: Add Proxmox No-Subscription repository
  apt_repository:
    repo: "deb http://download.proxmox.com/debian/pve {{ ansible_facts['distribution_release'] }} pve-no-subscription"
    state: present
    update_cache: no

- name: Add Debian Bookworm Repositories with non-free-firmware
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  loop:
    - "deb http://ftp.debian.org/debian {{ ansible_facts['distribution_release'] }} main contrib non-free-firmware"
    - "deb http://ftp.debian.org/debian {{ ansible_facts['distribution_release'] }}-updates main contrib non-free-firmware"
    - "deb http://security.debian.org/debian-security {{ ansible_facts['distribution_release'] }}-security main contrib non-free-firmware"

- name: Perform full system upgrade (dist-upgrade)
  apt:
    upgrade: dist
    update_cache: yes
  register: upgrade_result

- name: Install PowerTop
  apt:
    name: powertop
    state: present

- name: Enable PowerTop Auto-Tune on boot
  cron:
    name: "PowerTop Auto-Tune"
    special_time: reboot
    job: "/usr/sbin/powertop --auto-tune"
