services:
  - port: 8080
    subdomain: cloud
    icon: sh:nextcloud
    title: Nextcloud
    auth_type: oidc

app_dir_perms:
  - path: /nextcloud_data
    owner: "82"
    group: "82"
  - path: /common
    owner: "33"
    group: "33"
